[project]
name = "prh-warehouse-ingest"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "psutil>=5.9.0",
    "pyodbc>=5.2.0",
    "sqlmodel>=0.0.24",
]
