name: Reports Adhoc - DOMO

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Month to update in format YYYYMM (eg 202501)"
        required: true
        type: string

jobs:
  run-reports:
    runs-on: self-hosted
    steps:
      - name: Checkout prw-exporter
        uses: actions/checkout@v4
        with:
          repository: pullmanregional/prw-exporter
          token: ${{ secrets.DEPLOY_PAT }}
          path: prw-exporter
          submodules: true

      - name: Run script
        run: |
          pushd prw-exporter/reports/finance

          # Load env vars based on environment designated in PRW_ENV
          set -a; source ../.env.$PRW_ENV

          # Run script
          uv run python finance_domo.py --prw "$PRW_CONN" --out "$PRH_REPORTS_DOMO_PATH" --month "${{ inputs.month }}"
        env:
          PRW_ENV: ${{ env.PRW_ENV || 'prod' }}
          PRW_CONN: ${{ secrets.PRW_CONN_RO }}
          PRH_REPORTS_DOMO_PATH: ${{ vars.PRH_REPORTS_DOMO_PATH }}
